import streamlit as st
import pandas as pd
import numpy as np
from xgboost import XGBRegressor
from matminer.featurizers.composition import ElementProperty
from pymatgen.core import Composition
import warnings
warnings.filterwarnings("ignore")

st.set_page_config(
    page_title="Battery AI — Solid Electrolyte Predictor",
    page_icon="🔋",
    layout="centered"
)

@st.cache_resource
def load_model():
    model = XGBRegressor()
    model.load_model("models/xgb_ionic_v2.json")
    ep = ElementProperty.from_preset("magpie")
    return model, ep

model, ep = load_model()

def predict(formula):
    try:
        comp = Composition(formula)
        feats = ep.featurize(comp)
        log_pred = model.predict([feats])[0]
        return 10 ** log_pred, log_pred
    except:
        return None, None

# UI
st.title("🔋 Battery AI")
st.subheader("Solid Electrolyte Ionic Conductivity Predictor")
st.markdown("Predict the ionic conductivity of Li-based solid electrolyte materials using ML.")
st.divider()

# 입력
col1, col2 = st.columns([3, 1])
with col1:
    formula = st.text_input("Enter formula", placeholder="e.g. Li6PS5Cl, Li7La3Zr2O12")
with col2:
    predict_btn = st.button("Predict", type="primary", use_container_width=True)

# 예측
if predict_btn and formula:
    with st.spinner("Predicting..."):
        conductivity, log_conductivity = predict(formula)
    
    if conductivity is not None:
        st.success("Prediction complete!")
        
        col1, col2, col3 = st.columns(3)
        with col1:
            st.metric("Ionic Conductivity", f"{conductivity:.2e} S/cm")
        with col2:
            st.metric("log(Conductivity)", f"{log_conductivity:.2f}")
        with col3:
            if conductivity > 1e-3:
                grade = "🟢 Excellent"
            elif conductivity > 1e-4:
                grade = "🟡 Good"
            elif conductivity > 1e-6:
                grade = "🟠 Moderate"
            else:
                grade = "🔴 Poor"
            st.metric("Rating", grade)
        
        # 참고 기준
        st.markdown("**Reference benchmarks:**")
        ref = pd.DataFrame({
            "Material": ["Li6PS5Cl (Argyrodite)", "Li7La3Zr2O12 (LLZO)", "Li10GeP2S12 (LGPS)", "Your material"],
            "Conductivity (S/cm)": ["1e-3", "1e-4", "1.2e-2", f"{conductivity:.2e}"],
        })
        st.table(ref)
    else:
        st.error("Invalid formula. Please check and try again.")

st.divider()

# Top 20 후보
st.subheader("🏆 AI-Discovered Top Candidates")
st.markdown("Top 20 high-conductivity candidates generated by inverse design pipeline.")

df = pd.read_csv("data/validated_candidates_v2.csv")
df = df.sort_values("predicted_conductivity", ascending=False).head(20)
df["predicted_conductivity"] = df["predicted_conductivity"].apply(lambda x: f"{x:.2e}")
df = df.rename(columns={
    "formula": "Formula",
    "predicted_conductivity": "Predicted Conductivity (S/cm)",
    "matched_families": "Electrolyte Family",
    "stability_score": "Stability Score",
    "recommendation": "Rating"
})
st.dataframe(df[["Formula", "Predicted Conductivity (S/cm)", "Electrolyte Family", "Rating"]], use_container_width=True)

st.divider()
st.caption("Built with XGBoost + Magpie features | Data: Materials Project + OBELiX | R² = 0.675")
